--- 
- hosts: webservers
  become: yes
  tasks: 
        - name: i want to install java on ubuntu
          apt:
             name: "{{webserveronubuntu: openjdk-11-jre}}" 
             state: present
